from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd


def timestamp_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def model_version_label(bundle: dict | None = None) -> str:
    if bundle:
        selected = bundle.get("selected_model", {})
        name = selected.get("name") or "session_model"
        method = selected.get("calibration_method")
        return f"{name}:{method}" if method else name
    return "rf_model_v1"


def candidate_provenance(row, mode: str, source_name: str, model_version: str) -> str:
    source_smiles = row.get("source_smiles")
    molecule_id = row.get("molecule_id") or row.get("polymer")
    source_field = row.get("source")
    assay = str(row.get("assay") or "").strip()
    target = str(row.get("target") or "").strip()
    try:
        measurement_value = float(row.get("value"))
    except (TypeError, ValueError):
        measurement_value = None

    context_parts = []
    if assay:
        context_parts.append(f"assay {assay}")
    if target:
        context_parts.append(f"target {target}")
    if measurement_value is not None:
        context_parts.append(f"measured value {measurement_value:.3f}")
    context_text = f" Context: {', '.join(context_parts)}." if context_parts else ""

    if mode == "discovery" and source_smiles:
        return f"Generated from uploaded dataset using source molecule {source_smiles}. Model version: {model_version}.{context_text}"
    if mode == "discovery":
        return f"Generated by the internal discovery engine from {source_name}. Model version: {model_version}.{context_text}"
    if molecule_id:
        return f"Scored directly from user-uploaded dataset {source_name} for molecule {molecule_id}. Model version: {model_version}.{context_text}"
    if source_field:
        return f"Scored from user-uploaded dataset {source_name} using source {source_field}. Model version: {model_version}.{context_text}"
    return f"Scored directly from user-uploaded dataset {source_name}. Model version: {model_version}.{context_text}"


def add_candidate_provenance(
    df: pd.DataFrame,
    mode: str,
    source_name: str,
    bundle: dict | None = None,
    default_status: str = "suggested",
) -> pd.DataFrame:
    annotated = df.copy()
    model_version = model_version_label(bundle)
    timestamp = timestamp_now()

    if "status" not in annotated.columns:
        annotated["status"] = default_status
    annotated["timestamp"] = timestamp
    annotated["model_version"] = model_version
    annotated["provenance"] = annotated.apply(
        lambda row: candidate_provenance(row, mode=mode, source_name=source_name, model_version=model_version),
        axis=1,
    )
    return annotated
