from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd


def timestamp_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def model_version_label(bundle: dict | None = None) -> str:
    if bundle:
        selected = bundle.get("selected_model", {})
        name = selected.get("name") or "session_model"
        method = selected.get("calibration_method")
        return f"{name}:{method}" if method else name
    return "rf_model_v1"


def candidate_provenance(row, mode: str, source_name: str, model_version: str) -> str:
    source_smiles = row.get("source_smiles")
    molecule_id = row.get("molecule_id") or row.get("polymer")
    source_field = row.get("source")

    if mode == "discovery" and source_smiles:
        return f"Generated from uploaded dataset using source molecule {source_smiles}. Model version: {model_version}."
    if mode == "discovery":
        return f"Generated by the internal discovery engine from {source_name}. Model version: {model_version}."
    if molecule_id:
        return f"Scored directly from uploaded molecule {molecule_id}. Model version: {model_version}."
    if source_field:
        return f"Scored from uploaded source {source_field}. Model version: {model_version}."
    return f"Scored directly from user-uploaded dataset {source_name}. Model version: {model_version}."


def add_candidate_provenance(
    df: pd.DataFrame,
    mode: str,
    source_name: str,
    bundle: dict | None = None,
    default_status: str = "suggested",
) -> pd.DataFrame:
    annotated = df.copy()
    model_version = model_version_label(bundle)
    timestamp = timestamp_now()

    if "status" not in annotated.columns:
        annotated["status"] = default_status
    annotated["timestamp"] = timestamp
    annotated["model_version"] = model_version
    annotated["provenance"] = annotated.apply(
        lambda row: candidate_provenance(row, mode=mode, source_name=source_name, model_version=model_version),
        axis=1,
    )
    return annotated
